language: python
sudo: required
services:
  - docker
python:
  - 3.5
  - 3.5-dev
  - 3.6
  - 3.6-dev
  - nightly
install:
  - make install-dev
  - pip install coveralls
  - pip install docker
script:
  - make clean test
after_success:
  - coveralls
